CREATE TABLE
    t_scheduler_log
    (
        ID VARCHAR(255) NOT NULL,
        SCHEDULER_ID VARCHAR(100),
        JOB_NAME VARCHAR(100),
        JOB_DESC VARCHAR(100),
        HOST_NAME VARCHAR(100),
        HOST_ADDRESS VARCHAR(100),
        PREV_START_TIME DATETIME,
        PREV_RESULT VARCHAR(100),
        PREV_END_TIME DATETIME,
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    
CREATE TABLE
    t_scheduler_setting
    (
        ID VARCHAR(255) NOT NULL,
        SCHEDULER_ID VARCHAR(100),
        GROUP_ID VARCHAR(100),
        SCHEDULER_WAR VARCHAR(100),
        TRIGGER_NAME VARCHAR(100),
        JOB_NAME VARCHAR(100),
        DESCRIPTION VARCHAR(200),
        JOB_CLASS VARCHAR(300),
        MISFIRE_HANDLING INT,
        TYPE VARCHAR(1),
        ENABLE bit,
        CRON_EXPRESS VARCHAR(100),
        SIMPLE_START_TIME DATETIME,
        SIMPLE_END_TIME DATETIME,
        SIMPLE_REPEAT_COUNT INT,
        SIMPLE_REPEAT_INTERVEL INT,
        PARAM1 VARCHAR(100),
        PARAM2 VARCHAR(100),
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    
INSERT INTO t_pbl_scheduler_setting (ID, SCHEDULER_ID, GROUP_ID, SCHEDULER_WAR, TRIGGER_NAME, JOB_NAME, DESCRIPTION, JOB_CLASS, MISFIRE_HANDLING, TYPE, ENABLE, CRON_EXPRESS, SIMPLE_START_TIME, SIMPLE_END_TIME, SIMPLE_REPEAT_COUNT, SIMPLE_REPEAT_INTERVEL, PARAM1, PARAM2) 
  VALUES ('1', 'baseSchedule', 'wyjJobGroup', 'base-job', 'testTrigger1', 'testJob', 'testJob-testTrigger1', 'com.ey.piit.basejob.job.TestJob', 1, '1', true, '*/10 * * * * ?', '1015-07-17 00:00:00', '1015-07-17 00:00:00', 1, 1, '1', '2');
